local function InitializeSoundChat()	
	local scimodels = {
		["models/jheviv/jhevmk4.mdl"] = true,
		["models/player/hdpp/gordon.mdl"] = true,
		["models/player/hdpp/male_01.mdl"] = true,
		["models/player/hdpp/male_02.mdl"] = true,
		["models/player/hdpp/male_03.mdl"] = true,
		["models/player/hdpp/male_05.mdl"] = true,
		["models/player/hdpp/male_06.mdl"] = true,
		["models/player/hdpp/male_09.mdl"] = true,
		["models/Player/hdpp/barney.mdl"] = true,
		["models/player/hdpp/kleiner.mdl"] = true,
		["models/hazmat/bmhaztechs.mdl"] = true
	}

	local secmodels = {
		["models/player/hdpp/security/male_05.mdl"] = true,
		["models/player/hdpp/security/male_06.mdl"] = true,
		["models/player/hdpp/security/male_09.mdl"] = true,
		["models/player/hdpp/security/barney.mdl"] = true
	}

	local marinemodels = { ["models/player/gasmask_hecu.mdl"] = true }

	local cpmodels = {
		["models/player/hla/metropolice_pm.mdl"] = true,
		["models/dpfilms/metropolice/playermodels/pm_elite_police.mdl"] = true
	}

	local combinemodels = {
		["models/nemez/combine_soldiers/combine_soldier_pm.mdl"] = true,
		["models/nemez/combine_soldiers/combine_soldier_shotgunner_pm.mdl"] = true,
		["models/nemez/combine_soldiers/combine_soldier_coordinator_pm.mdl"] = true,
		["models/nemez/combine_soldiers/combine_soldier_urban_pm.mdl"] = true,
		["models/nemez/combine_soldiers/combine_soldier_urban_shotgunner_pm.mdl"] = true,
		["models/player/combine_soldier_prisonguard.mdl"] = true,
		["models/player/combine_super_soldier.mdl"] = true,
		["models/player/combine_soldier.mdl"] = true
	}

	local femalemodels = {
		["models/player/group01/female_01.mdl"] = true,
		["models/player/group01/female_02.mdl"] = true,
		["models/player/group01/female_03.mdl"] = true,
		["models/player/group01/female_04.mdl"] = true,
		["models/player/group01/female_06.mdl"] = true,
		["models/player/group03/female_01.mdl"] = true,
		["models/player/group03/female_02.mdl"] = true,
		["models/player/group03/female_03.mdl"] = true,
		["models/player/group03/female_04.mdl"] = true,
		["models/player/group03/female_05.mdl"] = true,
		["models/player/group03/female_06.mdl"] = true,
		["models/willardnetworks_custom/citizens/female_01.mdl"] = true,
		["models/willardnetworks_custom/citizens/female_02.mdl"] = true,
		["models/willardnetworks_custom/citizens/female_03.mdl"] = true,
		["models/willardnetworks_custom/citizens/female_04.mdl"] = true,
		["models/willardnetworks_custom/citizens/female_06.mdl"] = true,
		["models/willardnetworks_custom/citizens/female_07.mdl"] = true
	}

	local malemodels = {
		["models/player/group01/male_01.mdl"] = true,
		["models/player/group01/male_02.mdl"] = true,
		["models/player/group01/male_03.mdl"] = true,
		["models/player/group01/male_04.mdl"] = true,
		["models/player/group01/male_05.mdl"] = true,
		["models/player/group01/male_06.mdl"] = true,
		["models/player/group01/male_07.mdl"] = true,
		["models/player/group01/male_08.mdl"] = true,
		["models/player/group01/male_09.mdl"] = true,
		["models/player/group03/male_01.mdl"] = true,
		["models/player/group03/male_02.mdl"] = true,
		["models/player/group03/male_03.mdl"] = true,
		["models/player/group03/male_04.mdl"] = true,
		["models/player/group03/male_05.mdl"] = true,
		["models/player/group03/male_06.mdl"] = true,
		["models/player/group03/male_07.mdl"] = true,
		["models/player/group03/male_08.mdl"] = true,
		["models/player/group03/male_09.mdl"] = true,
		["models/willardnetworks_custom/citizens/male01.mdl"] = true,
		["models/willardnetworks_custom/citizens/male02.mdl"] = true,
		["models/willardnetworks_custom/citizens/male03.mdl"] = true,
		["models/willardnetworks_custom/citizens/male04.mdl"] = true,
		["models/willardnetworks_custom/citizens/male05.mdl"] = true,
		["models/willardnetworks_custom/citizens/male06.mdl"] = true,
		["models/willardnetworks_custom/citizens/male07.mdl"] = true,
		["models/willardnetworks_custom/citizens/male08.mdl"] = true,
		["models/willardnetworks_custom/citizens/male09.mdl"] = true
	}

	local scichats = {
		{ "absolutely", "scientist/absolutely.wav" },
		{ "not", "scientist/absolutelynot.wav" },
		{ "appeal", "scientist/alienappeal.wav" },
		{ "administrator", "scientist/administrator.wav" },
		{ "fellow", "scientist/afellowsci.wav" },
		{ "nominal", "scientist/allnominal.wav" },
		{ "alright", "scientist/alright.wav" },
		{ "looking", "scientist/analysis.wav" },
		{ "analysis", "scientist/analysis.wav" },
		{ "thinking", "scientist/areyouthink.wav" },
		{ "expect", "scientist/asexpected.wav" },
		{ "beverage", "scientist/beverage.wav" },
		{ "blood", "scientist/bloodsample.wav" },
		{ "its you", "scientist/c1a0_sci_itsyou.wav" },
		{ "it's you", "scientist/c1a0_sci_itsyou.wav" },
		{ "ahem", "scientist/c1a0_sci_stall.wav" },
		{ "run", "scientist/c1a2_sci_1zomb.wav" },
		{ "rescued", "scientist/c1a3_sci_rescued.wav" },
		{ "doomed", "scientist/c1a3_sci_silo2a.wav" },
		{ "don't shoot", "scientist/c1a3_sci_team.wav" },
		{ "dont shoot", "scientist/c1a3_sci_team.wav" },
		{ "cant see", "scientist/c1a4_sci_blind.wav" },
		{ "can't see", "scientist/c1a4_sci_blind.wav" },
		{ "our fault", "scientist/c2a4_sci_arg2a.wav" },
		{ "get it off", "scientist/c1a4_sci_tent.wav" },
		{ "over here", "scientist/c3a2_sci_1glu.wav" },
		{ "fool", "scientist/c3a2_sci_fool.wav" },
		{ "serious", "scientist/cantbeserious.wav" },
		{ "get worse", "scientist/cantbeworse.wav" },
		{ "cascade", "scientist/cascade.wav" },
		{ "specimen", "scientist/catchone.wav" },
		{ "wrong", "scientist/completelywrong.wav" },
		{ "containment", "scientist/containfail.wav" },
		{ "theory", "scientist/correcttheory.wav" },
		{ "hear", "scientist/didyouhear.wav" },
		{ "idk", "scientist/dontknow.wav" },
		{ "dont know", "scientist/dontknow.wav" },
		{ "don't know", "scientist/dontknow.wav" },
		{ "donut", "scientist/donuteater.wav" },
		{ "seen", "scientist/everseen.wav" },
		{ "greetings", "scientist/greetings.wav" },
		{ "headcrab", "scientist/headcrab.wav" },
		{ "hi", "scientist/hello.wav" },
		{ "hello", "scientist/hello.wav" },
		{ "glasses", "scientist/hideglasses.wav" },
		{ "hope", "scientist/hopeyouknow.wav" },
		{ "interesting", "scientist/howinteresting.wav" },
		{ "hungry", "scientist/hungryyet.wav" },
		{ "believe", "scientist/ibelieveso.wav" },
		{ "sure", "scientist/imsure.wav" },
		{ "lets go", "scientist/letsgo.wav" },
		{ "let's go", "scientist/letsgo.wav" },
		{ "predict", "scientist/ipredictedthis.wav" },
		{ "try this", "scientist/letstrythis.wav" },
		{ "quiet", "scientist/lowervoice.wav" },
		{ "madness", "scientist/madness.wav" },
		{ "fascinating", "scientist/neverseen.wav" },
		{ "amazing", "scientist/neverseen.wav" },
		{ "sample", "scientist/newsample.wav" },
		{ "doubt", "scientist/nodoubt.wav" },
		{ "no", "scientist/noo.wav" },
		{ "noo", "scientist/nooo.wav" },
		{ "smell", "scientist/odorfromyou.wav" },
		{ "of course", "scientist/ofcourse.wav" },
		{ "right", "scientist/right.wav" },
		{ "get back", "scientist/sci_fear14.wav" },
		{ "ah", "scientist/sci_fear8.wav" },
		{ "coffee", "scientist/seencup.wav" },
		{ "report", "scientist/statusreport.wav" },
		{ "shut up", "scientist/shutup2.wav" },
		{ "uh oh", "scientist/startle9.wav" },
		{ "odd", "scientist/thatsodd.wav" },
		{ "theoretically", "scientist/theoretically.wav" },
		{ "look", "scientist/ushouldsee.wav" },
		{ "wait", "scientist/waithere.wav" },
		{ "tie", "scientist/weartie.wav" },
		{ "now what", "scientist/whatnext.wav" },
		{ "what", "scientist/whatyoudoing.wav" },
		{ "yes", "scientist/yes.wav" },
		{ "yea", "scientist/yes.wav" },
		{ "yey", "scientist/yes.wav" },
		{ "ok", "scientist/yesok.wav" },
		{ "okay", "scientist/yesok.wav" },
		{ "insane", "scientist/youinsane.wav" },
		{ "perhaps", "scientist/perhaps.wav" }
	}

	local secchats = {
		{ "aim", "barney/aimforhead.wav" },
		{ "not going", "barney/aintgoin.wav" },
		{ "scared", "barney/aintscared.wav" },
		{ "ambush", "barney/ambush.wav" },
		{ "bring it", "barney/ba_bring.wav" },
		{ "freeze", "barney/ba_attack1.wav" },
		{ "that was close", "barney/ba_close.wav" },
		{ "friend", "barney/ba_friends.wav" },
		{ "beer", "barney/ba_later.wav" },
		{ "step off", "barney/ba_stepoff.wav" },
		{ "watch it", "barney/ba_watchit.wav" },
		{ "bad feeling", "barney/badfeeling.wav" },
		{ "quiet", "barney/bequiet.wav" },
		{ "mess", "barney/bigmess.wav" },
		{ "go right on through", "barney/c1a0_ba_hevyes.wav" },
		{ "shit", "barney/c1a2_ba_4zomb.wav" },
		{ "stair", "barney/c1a2_ba_climb.wav" },
		{ "eat lead", "barney/c1a4_ba_octo1.wav" },
		{ "take me down", "barney/c1a4_ba_octo2.wav" },
		{ "ah", "barney/c1a4_ba_octo3.wav" },
		{ "bastard", "barney/c1a4_ba_octo4.wav" },
		{ "leave me", "barney/c2a1_ba_hub2a.wav" },
		{ "get in", "barney/c2a4_ba_steril.wav" },
		{ "let me out", "barney/c2a5_ba_letout.wav" },
		{ "die", "barney/diebloodsucker.wav" },
		{ "don't think", "barney/dontguess.wav" },
		{ "dont think", "barney/dontguess.wav" },
		{ "stop", "barney/donthurtem.wav" },
		{ "doubt", "barney/dontreckon.wav" },
		{ "hear", "barney/hearsomething2.wav" },
		{ "sir", "barney/hayfella.wav" },
		{ "hi", "barney/hellonicesuit.wav" },
		{ "hello", "barney/hellonicesuit.wav" },
		{ "i guess", "barney/iguess.wav" },
		{ "lets go", "barney/letsgo.wav" },
		{ "let's go", "barney/letsgo.wav" },
		{ "rodger", "barney/letsmoveit.wav" },
		{ "roger", "barney/letsmoveit.wav" },
		{ "maybe", "barney/maybe.wav" },
		{ "no", "barney/nope.wav" },
		{ "nope", "barney/nope.wav" },
		{ "cya", "barney/seeya.wav" },
		{ "bye", "barney/seeya.wav" },
		{ "look", "barney/somethingmoves.wav" },
		{ "smell", "barney/somethingstinky.wav" },
		{ "right", "barney/soundsright.wav" },
		{ "stand back", "barney/standback.wav" },
		{ "target", "barney/targetpractice.wav" },
		{ "thinking", "barney/thinking.wav" },
		{ "wait", "barney/waitin.wav" },
		{ "the hell", "barney/whatisthat.wav" },
		{ "what's going on", "barney/whatsgoingon.wav" },
		{ "whats going on", "barney/whatsgoingon.wav" },
		{ "yup", "barney/yup.wav" },
		{ "yep", "barney/yup.wav" },
		{ "got it", "barney/yougotit.wav" },
		{ "yes", "barney/yessir.wav" },
		{ "yea", "barney/yessir.wav" }
	}

	local marinechats = {
		{ "clear", "fgrunt/allclear.wav" },
		{ "bad feeling", "fgrunt/bfeeling.wav" },
		{ "bogie", "fgrunt/bogies.wav" },
		{ "check", "fgrunt/check.wav" },
		{ "take cover", "fgrunt/cover.wav" },
		{ "get down", "fgrunt/down.wav" },
		{ "fubar", "fgrunt/fubar.wav" },
		{ "go", "fgrunt/go.wav" },
		{ "hi", "fgrunt/hellosir.wav" },
		{ "hello", "fgrunt/hellosir.wav" },
		{ "incoming", "fgrunt/incoming.wav" },
		{ "lets go", "fgrunt/marines.wav" },
		{ "let's go", "fgrunt/marines.wav" },
		{ "medic", "fgrunt/medic.wav" },
		{ "no", "fgrunt/no.wav" },
		{ "nope", "fgrunt/no.wav" },
		{ "negative", "fgrunt/no.wav" },
		{ "quiet", "fgrunt/quiet.wav" },
		{ "rodger", "fgrunt/roger.wav" },
		{ "roger", "fgrunt/roger.wav" },
		{ "sir", "fgrunt/sir_01.wav" },
		{ "thanks", "fgrunt/thanks.wav" },
		{ "yes", "fgrunt/yes.wav" },
		{ "yea", "fgrunt/yes.wav" }
	}

	local cpchat = {
		{ "tag one parasitic", "npc/metropolice/vo/tagoneparasitic.wav" },
		{ "tag one necrotic", "npc/metropolice/vo/tagonenecrotic.wav" },
		{ "11 99", "npc/metropolice/vo/11-99officerneedsassistance.wav" },
		{ "1199", "npc/metropolice/vo/11-99officerneedsassistance.wav" },
		{ "administer", "npc/metropolice/vo/administer.wav" },
		{ "affirmative", "npc/metropolice/vo/affirmative2.wav" },
		{ "affirm", "npc/metropolice/vo/affirmative.wav" },
		{ "airwatch", "npc/metropolice/vo/airwatchsubjectis505.wav" },
		{ "you can go", "npc/metropolice/vo/allrightyoucango.wav" },
		{ "code 2", "npc/metropolice/vo/allunitscode2.wav" },
		{ "move in", "npc/metropolice/vo/allunitsmovein.wav" },
		{ "anticitizen", "npc/metropolice/vo/anticitizen.wav" },
		{ "apply", "npc/metropolice/vo/apply.wav" },
		{ "backup", "npc/metropolice/vo/backup.wav" },
		{ "bugs", "npc/metropolice/vo/bugsontheloose.wav" },
		{ "cauterize", "npc/metropolice/vo/cauterize.wav" },
		{ "haha", "npc/metropolice/vo/chuckle.wav" },
		{ "code 100", "npc/metropolice/vo/clearandcode100.wav" },
		{ "cover me", "npc/metropolice/vo/covermegoingin.wav" },
		{ "defender", "npc/metropolice/vo/defender.wav" },
		{ "document", "npc/metropolice/vo/document.wav" },
		{ "stop", "npc/metropolice/vo/dontmove.wav" },
		{ "dont move", "npc/metropolice/vo/dontmove.wav" },
		{ "don't move", "npc/metropolice/vo/dontmove.wav" },
		{ "examine", "npc/metropolice/vo/examine.wav" },
		{ "get down", "npc/metropolice/vo/getdown.wav" },
		{ "hold it right there", "npc/metropolice/vo/holditrightthere.wav" },
		{ "infection", "npc/metropolice/vo/infection.wav" },
		{ "inject", "npc/metropolice/vo/inject.wav" },
		{ "rodger", "npc/metropolice/vo/rodgerthat.wav" },
		{ "responding", "npc/metropolice/vo/responding.wav" },
		{ "shots fired", "npc/metropolice/vo/shotsfiredhostilemalignants.wav" },
		{ "sterilize", "npc/metropolice/vo/sterilize.wav" },
		{ "zero", "npc/metropolice/vo/zero.wav" },
		{ "0", "npc/metropolice/vo/zero.wav" },
		{ "xray", "npc/metropolice/vo/xray.wav" },
		{ "yellow", "npc/metropolice/vo/yellow.wav" },
		{ "wrap it up", "npc/combine_soldier/vo/thatsitwrapitup.wav" },
		{ "workforce", "npc/metropolice/vo/workforceintake.wav" },
		{ "winder", "npc/combine_soldier/vo/winder.wav" },
		{ "watch it", "npc/metropolice/vo/watchit.wav" },
		{ "wasteriver", "npc/metropolice/vo/wasteriver.wav" },
		{ "second warning given", "npc/metropolice/vo/secondwarning.wav" },
		{ "visual exogen", "npc/combine_soldier/vo/visualonexogens.wav" },
		{ "viscon", "npc/combine_soldier/vo/viscon.wav" },
		{ "victor", "npc/metropolice/vo/victor.wav" },
		{ "vice", "npc/metropolice/vo/vice.wav" },
		{ "you want a malcompliance verdict", "npc/metropolice/vo/youwantamalcomplianceverdict.wav" },
		{ "you want malcompliance", "npc/metropolice/vo/youwantamalcomplianceverdict.wav" },
		{ "vamp", "npc/combine_soldier/vo/vamp.wav"},
		{ "vacate", "npc/metropolice/vo/vacatecitizen.wav" },
		{ "utl suspect", "npc/metropolice/vo/utlthatsuspect.wav" },
		{ "utl", "npc/metropolice/vo/utlsuspect.wav" },
		{ "upi", "npc/metropolice/vo/upi.wav" },
		{ "up there", "npc/metropolice/vo/hesupthere.wav" },
		{ "suspect location unknown", "npc/metropolice/vo/suspectlocationunknown.wav" },
		{ "union", "npc/metropolice/vo/union.wav" },
		{ "uniform", "npc/combine_soldier/vo/uniform.wav" },
		{ "under fire", "npc/metropolice/vo/officerunderfiretakingcover.wav" },
		{ "trouble", "npc/metropolice/vo/lookingfortrouble.wav" },
		{ "transitblock", "npc/metropolice/vo/transitblock.wav" },
		{ "tracker", "npc/combine_soldier/vo/tracker.wav" },
		{ "there he is", "npc/metropolice/vo/thereheis.wav" },
		{ "team advance", "npc/metropolice/vo/teaminpositionadvance.wav" },
		{ "tap", "npc/metropolice/vo/tap.wav" },
		{ "take cover", "npc/metropolice/vo/takecover.wav" },
		{ "take a look", "npc/metropolice/vo/goingtotakealook.wav" },
		{ "tag one bug", "npc/metropolice/vo/tagonebug.wav" },
		{ "tag one necrotic", "npc/metropolice/vo/tagonenecrotic.wav" },
		{ "tag one parasitic", "npc/metropolice/vo/tagoneparasitic.wav" },
		{ "tag 10-91d", "npc/metropolice/vo/tag10-91d.wav" },
		{ "sword", "npc/combine_soldier/vo/sword.wav" },
		{ "swift", "npc/combine_soldier/vo/swift.wav" },
		{ "sweeping suspect", "npc/metropolice/vo/sweepingforsuspect.wav" },
		{ "sweeping in", "npc/combine_soldier/vo/sweepingin.wav" },
		{ "sweeper", "npc/combine_soldier/vo/sweeper.wav" },
		{ "suspend", "npc/metropolice/vo/suspend.wav" },
		{ "suspect moved to", "npc/metropolice/vo/supsecthasmovednowto.wav" },
		{ "suspect incursion", "npc/metropolice/vo/dispreportssuspectincursion.wav" },
		{ "subject", "npc/metropolice/vo/subject.wav" },
		{ "subject is 505", "npc/metropolice/vo/subjectis505.wav" },
		{ "striker", "npc/combine_soldier/vo/striker.wav" },
		{ "storm", "npc/combine_soldier/vo/storm.wav" },
		{ "stinger", "npc/combine_soldier/vo/stinger.wav" },
		{ "stay alert", "npc/combine_soldier/vo/stayalert.wav" },
		{ "stationblock", "npc/metropolice/vo/stationblock.wav" },
		{ "star", "npc/combine_soldier/vo/star.wav" },
		{ "stab", "npc/combine_soldier/vo/stab.wav" },
		{ "spear", "npc/combine_soldier/vo/spear.wav" },
		{ "slash", "npc/combine_soldier/vo/slash.wav" },
		{ "slam", "npc/combine_soldier/vo/slam.wav" },
		{ "sociostable", "npc/metropolice/vo/wearesociostablethislocation.wav" },
		{ "shots fired", "npc/metropolice/vo/shotsfiredhostilemalignants.wav" },
		{ "serve", "npc/metropolice/vo/serve.wav" },
		{ "sentence delivered", "npc/metropolice/vo/sentencedelivered.wav" },
		{ "secure advance", "npc/metropolice/vo/assaultpointsecureadvance.wav" },
		{ "sector not secure", "npc/combine_soldier/vo/sectorisnotsecure.wav" },
		{ "sector not sterile", "npc/combine_soldier/vo/confirmsectornotsterile.wav" },
		{ "second warning", "npc/metropolice/vo/thisisyoursecondwarning.wav" },
		{ "searching for suspect", "npc/metropolice/vo/searchingforsuspect.wav" },
		{ "search", "npc/metropolice/vo/search.wav" },
		{ "scar", "npc/combine_soldier/vo/scar.wav" },
		{ "savage", "npc/combine_soldier/vo/savage.wav" },
		{ "secure", "npc/combine_soldier/vo/secure.wav" },
		{ "sacrifice code", "npc/metropolice/vo/sacrificecode1maintaincp.wav" },
		{ "hes running", "npc/metropolice/vo/hesrunning.wav" },
		{ "roller", "npc/metropolice/vo/roller.wav" },
		{ "ripcord", "npc/combine_soldier/vo/ripcord.wav" },
		{ "restriction zone", "npc/metropolice/vo/terminalrestrictionzone.wav" },
		{ "restricted block", "npc/metropolice/vo/restrictedblock.wav" },
		{ "restrict", "npc/metropolice/vo/restrict.wav" },
		{ "responding", "npc/metropolice/vo/responding2.wav" },
		{ "respond code 3", "npc/metropolice/vo/allunitsrespondcode3.wav" },
		{ "residential block", "npc/metropolice/vo/residentialblock.wav" },
		{ "repurposed area", "npc/metropolice/vo/repurposedarea.wav" },
		{ "report status", "npc/metropolice/vo/localcptreportstatus.wav" },
		{ "report suspect location", "npc/metropolice/vo/allunitsreportlocationsuspect.wav" },
		{ "report location of suspect", "npc/metropolice/vo/allunitsreportlocationsuspect.wav" },
		{ "report in", "npc/metropolice/vo/cprequestsallunitsreportin.wav" },
		{ "reporting clear", "npc/combine_soldier/vo/reportingclear.wav" },
		{ "code 3 to my 1020", "npc/metropolice/vo/officerdowncode3tomy10-20.wav" },
		{ "code 3 to my 10 20", "npc/metropolice/vo/officerdowncode3tomy10-20.wav" },
		{ "code 3", "npc/metropolice/vo/reinforcementteamscode3.wav" },
		{ "reaper", "npc/combine_soldier/vo/reaper.wav" },
		{ "ready weapons", "npc/combine_soldier/vo/readyweapons.wav" },
		{ "ready prosecute", "npc/metropolice/vo/readytoprosecute.wav" },
		{ "ready to prosecute", "npc/metropolice/vo/readytoprosecute.wav" },
		{ "ready judge", "npc/metropolice/vo/readytojudge.wav" },
		{ "ready to judge", "npc/metropolice/vo/readytojudge.wav" },
		{ "ready amputate", "npc/metropolice/vo/readytoamputate.wav" },
		{ "ready to amputate", "npc/metropolice/vo/readytoamputate.wav" },
		{ "amputate", "npc/metropolice/vo/amputate.wav" },
		{ "ready charges", "npc/combine_soldier/vo/readycharges.wav" },
		{ "razor", "npc/combine_soldier/vo/razor.wav" },
		{ "ranger", "npc/combine_soldier/vo/ranger.wav" },
		{ "range", "npc/combine_soldier/vo/range.wav" },
		{ "quick", "npc/metropolice/vo/quick.wav" },
		{ "protection complete", "npc/metropolice/vo/protectioncomplete.wav" },
		{ "prosecute malcompliant", "npc/metropolice/vo/readytoprosecutefinalwarning.wav" },
		{ "final warning given", "npc/metropolice/vo/readytoprosecutefinalwarning.wav" },
		{ "final warning issued", "npc/metropolice/vo/readytoprosecutefinalwarning.wav" },
		{ "prosecute", "npc/metropolice/vo/prosecute.wav" },
		{ "prosecuting", "npc/combine_soldier/vo/prosecuting.wav" },
		{ "production block", "npc/metropolice/vo/productionblock.wav" },
		{ "priority 1", "npc/metropolice/vo/confirmpriority1sighted.wav" },
		{ "priority 2", "npc/metropolice/vo/priority2anticitizenhere.wav" },
		{ "pressure", "npc/metropolice/vo/pressure.wav" },
		{ "preserve", "npc/metropolice/vo/preserve.wav" },
		{ "preparing to judge", "npc/metropolice/vo/preparingtojudge10-107.wav" },
		{ "possible level 3", "npc/metropolice/vo/possiblelevel3civilprivacyviolator.wav" },
		{ "possible accomplice", "npc/metropolice/vo/reportsightingsaccomplices.wav" },
		{ "possible 647e", "npc/metropolice/vo/possible647erequestairwatch.wav" },
		{ "position to contain", "npc/metropolice/vo/positiontocontain.wav" },
		{ "position at hardpoint", "npc/metropolice/vo/inpositionathardpoint.wav" },
		{ "phantom", "npc/combine_soldier/vo/phantom.wav" },
		{ "payback", "npc/combine_soldier/vo/payback.wav" },
		{ "patrol", "npc/metropolice/vo/patrol.wav" },
		{ "pain4", "npc/metropolice/pain4.wav" },
		{ "pain3", "npc/metropolice/pain3.wav" },
		{ "pain2", "npc/metropolice/pain2.wav" },
		{ "pain1", "npc/metropolice/pain1.wav" },
		{ "pacifying", "npc/metropolice/vo/pacifying.wav" },
		{ "overwatch", "npc/combine_soldier/vo/overwatch.wav" },
		{ "outbreak", "npc/metropolice/vo/outbreak.wav" },
		{ "now get out", "npc/metropolice/vo/nowgetoutofhere.wav" },
		{ "now", "vo/trainyard/ba_thatbeer01.wav" },
		{ "nova", "npc/combine_soldier/vo/nova.wav" },
		{ "nontagged viromes", "npc/metropolice/vo/non-taggedviromeshere.wav" },
		{ "nonpatrol", "npc/metropolice/vo/nonpatrolregion.wav" },
		{ "noncitizen", "npc/metropolice/vo/noncitizen.wav" },
		{ "nomad", "npc/combine_soldier/vo/nomad.wav" },
		{ "no visual on", "npc/metropolice/vo/novisualonupi.wav" },
		{ "no im good", "vo/trainyard/ba_noimgood.wav" },
		{ "no i'm good", "vo/trainyard/ba_noimgood.wav" },
		{ "nah i'm good", "vo/trainyard/ba_noimgood.wav" },
		{ "no contact", "npc/metropolice/vo/nocontact.wav" },
		{ "no 647", "npc/metropolice/vo/clearno647no10-107.wav" },
		{ "needs help", "npc/metropolice/vo/officerneedshelp.wav" },
		{ "needs assistance", "npc/metropolice/vo/officerneedsassistance.wav" },
		{ "need any help", "npc/metropolice/vo/needanyhelpwiththisone.wav" },
		{ "moving to hardpoint", "npc/metropolice/vo/movingtohardpoint.wav" },
		{ "moving to cover", "npc/metropolice/vo/movingtocover.wav" },
		{ "move it", "npc/metropolice/vo/moveit.wav" },
		{ "move back", "npc/metropolice/vo/movebackrightnow.wav" },
		{ "move along", "npc/metropolice/vo/movealong.wav" },
		{ "minor hits", "npc/metropolice/vo/minorhitscontinuing.wav" },
		{ "match on apb", "npc/metropolice/vo/matchonapblikeness.wav" },
		{ "malignant", "npc/metropolice/vo/malignant.wav" },
		{ "malcompliant 10107", "npc/metropolice/vo/malcompliant10107my1020.wav" },
		{ "malcompliant 10 107", "npc/metropolice/vo/malcompliant10107my1020.wav" },
		{ "malcompliance", "npc/metropolice/vo/issuingmalcompliantcitation.wav" },
		{ "maintain cp", "npc/metropolice/vo/allunitsmaintainthiscp.wav" },
		{ "mace", "npc/combine_soldier/vo/mace.wav" },
		{ "loose parasitics", "npc/metropolice/vo/looseparasitics.wav" },
		{ "look out", "npc/metropolice/vo/lookout.wav" },
		{ "lock position", "npc/metropolice/vo/lockyourposition.wav" },
		{ "lock", "npc/metropolice/vo/lock.wav" },
		{ "line", "npc/metropolice/vo/line.wav" },
		{ "level 3", "npc/metropolice/vo/level3civilprivacyviolator.wav" },
		{ "leader", "npc/combine_soldier/vo/leader.wav" },
		{ "king", "npc/metropolice/vo/king.wav" },
		{ "kilo", "npc/combine_soldier/vo/kilo.wav" },
		{ "keep moving", "npc/metropolice/vo/keepmoving.wav" },
		{ "jury", "npc/metropolice/vo/jury.wav" },
		{ "prepare for judgement", "npc/metropolice/vo/prepareforjudgement.wav" },
		{ "judge", "npc/combine_soldier/vo/judge.wav" },
		{ "jet", "npc/combine_soldier/vo/jet.wav" },
		{ "isolate", "npc/metropolice/vo/isolate.wav" },
		{ "is ready to go", "npc/metropolice/vo/isreadytogo.wav" },
		{ "is passive", "npc/metropolice/vo/ispassive.wav" },
		{ "is moving in", "npc/combine_soldier/vo/unitismovingin.wav" },
		{ "is inbound", "npc/combine_soldier/vo/unitisinbound.wav" },
		{ "unit inbound", "npc/combine_soldier/vo/unitisinbound.wav" },
		{ "is moving", "npc/metropolice/vo/ismovingin.wav" },
		{ "is down", "npc/metropolice/vo/isdown.wav" },
		{ "is closing", "npc/metropolice/vo/isclosingonsuspect.wav" },
		{ "is 108", "npc/metropolice/vo/unitis10-8standingby.wav" },
		{ "is 10 8", "npc/metropolice/vo/unitis10-8standingby.wav" },
		{ "is 10108", "npc/metropolice/vo/is10-108.wav" },
		{ "is 10 108", "npc/metropolice/vo/is10-108.wav" },
		{ "investigating 10103", "npc/metropolice/vo/investigating10-103.wav" },
		{ "investigating 10 103", "npc/metropolice/vo/investigating10-103.wav" },
		{ "ion", "npc/combine_soldier/vo/ion.wav" },
		{ "investigate", "npc/metropolice/vo/investigate.wav" },
		{ "interlock", "npc/metropolice/vo/interlock.wav" },
		{ "intercede", "npc/metropolice/vo/intercede.wav" },
		{ "inoculate", "npc/metropolice/vo/innoculate.wav" },
		{ "infested zone", "npc/metropolice/vo/infestedzone.wav" },
		{ "infection", "npc/metropolice/vo/infection.wav" },
		{ "infected", "npc/combine_soldier/vo/infected.wav" },
		{ "inbound", "npc/combine_soldier/vo/inbound.wav" },
		{ "in position", "npc/metropolice/vo/inposition.wav" },
		{ "ice", "npc/combine_soldier/vo/ice.wav" },
		{ "i said move", "npc/metropolice/vo/Isaidmovealong.wav" },
		{ "hurricane", "npc/combine_soldier/vo/hurricane.wav" },
		{ "hunter", "npc/combine_soldier/vo/hunter.wav" },
		{ "hold this position", "npc/metropolice/vo/holdthisposition.wav" },
		{ "hold", "npc/metropolice/vo/holdit.wav" },
		{ "high priority region", "npc/metropolice/vo/highpriorityregion.wav" },
		{ "hpr", "npc/metropolice/vo/highpriorityregion.wav" },
		{ "hes 148", "npc/metropolice/vo/hesgone148.wav" },
		{ "hero", "npc/metropolice/vo/hero.wav" },
		{ "help", "npc/metropolice/vo/help.wav" },
		{ "helix", "npc/combine_soldier/vo/helix.wav" },
		{ "hardpoint scanning", "npc/metropolice/vo/hardpointscanning.wav" },
		{ "is at hardpoint", "npc/metropolice/vo/isathardpointreadytoprosecute.wav" },
		{ "hammer", "npc/combine_soldier/vo/hammer.wav" },
		{ "grid", "npc/combine_soldier/vo/grid.wav" },
		{ "grenade", "npc/metropolice/vo/grenade.wav" },
		{ "got suspect 1", "npc/metropolice/vo/gotsuspect1here.wav" },
		{ "got suspect one", "npc/metropolice/vo/gotsuspect1here.wav" },
		{ "got one accomplice", "npc/metropolice/vo/gotoneaccomplicehere.wav" },
		{ "got 1 accomplice", "npc/metropolice/vo/gotoneaccomplicehere.wav" },
		{ "got a db", "npc/metropolice/vo/wegotadbherecancel10-102.wav" },
		{ "going in", "npc/metropolice/vo/covermegoingin.wav" },
		{ "go sharp", "npc/combine_soldier/vo/gosharp.wav" },
		{ "go again", "npc/metropolice/vo/ptgoagain.wav" },
		{ "ghost", "npc/combine_soldier/vo/ghost.wav" },
		{ "getting 647e", "npc/metropolice/vo/stillgetting647e.wav" },
		{ "get out", "npc/metropolice/vo/getoutofhere.wav" },
		{ "free necrotics", "npc/metropolice/vo/freenecrotics.wav" },
		{ "flush", "npc/combine_soldier/vo/flush.wav" },
		{ "flatline", "npc/combine_soldier/vo/flatline.wav" },
		{ "flash", "npc/combine_soldier/vo/flash.wav" },
		{ "fist", "npc/combine_soldier/vo/fist.wav" },
		{ "first warning", "npc/metropolice/vo/firstwarningmove.wav" },
		{ "final warning", "npc/metropolice/vo/finalwarning.wav" },
		{ "third warning", "npc/metropolice/vo/finalwarning.wav" },
		{ "last warning", "npc/metropolice/vo/finalwarning.wav" },
		{ "final verdict", "npc/metropolice/vo/finalverdictadministered.wav" },
		{ "external juridstiction", "npc/metropolice/vo/externaljurisdiction.wav" },
		{ "expose target", "npc/metropolice/vo/firingtoexposetarget.wav" },
		{ "establish new cp", "npc/metropolice/vo/establishnewcp.wav" },
		{ "engaging", "npc/combine_soldier/vo/engaging.wav" },
		{ "echo", "npc/combine_soldier/vo/echo.wav" },
		{ "distribution block", "npc/metropolice/vo/distributionblock.wav" },
		{ "disp apb", "npc/metropolice/vo/dispupdatingapb.wav" },
		{ "dismounting hardpoint", "npc/metropolice/vo/dismountinghardpoint.wav" },
		{ "dislocate interpose", "npc/metropolice/vo/firetodislocateinterpose.wav" },
		{ "destroy cover", "npc/metropolice/vo/destroythatcover.wav" },
		{ "deserviced area", "npc/metropolice/vo/deservicedarea.wav" },
		{ "defender", "npc/metropolice/vo/defender.wav" },
		{ "dash", "npc/combine_soldier/vo/dash.wav" },
		{ "dagger", "npc/combine_soldier/vo/dagger.wav" },
		{ "cp overrun", "npc/metropolice/vo/cpisoverrunwehavenocontainment.wav" },
		{ "cp establish", "npc/metropolice/vo/cpweneedtoestablishaperimeterat.wav" },
		{ "cp compromised", "npc/metropolice/vo/cpiscompromised.wav" },
		{ "copy that", "npc/combine_soldier/vo/copythat.wav" },
		{ "copy", "npc/metropolice/vo/copy.wav" },
		{ "converging", "npc/metropolice/vo/converging.wav" },
		{ "controlsection", "npc/metropolice/vo/controlsection.wav" },
		{ "control section", "npc/metropolice/vo/controlsection.wav" },
		{ "control 100", "npc/metropolice/vo/control100percent.wav" },
		{ "contained", "npc/combine_soldier/vo/contained.wav" },
		{ "contact priority", "npc/metropolice/vo/contactwithpriority2.wav" },
		{ "contact 243", "npc/metropolice/vo/contactwith243suspect.wav" },
		{ "contact", "npc/combine_soldier/vo/contact.wav" },
		{ "condemned", "npc/metropolice/vo/condemnedzone.wav" },
		{ "code 7", "npc/metropolice/vo/code7.wav" },
		{ "code 2", "npc/metropolice/vo/allunitscode2.wav" },
		{ "code 100", "npc/metropolice/vo/code100.wav" },
		{ "closing", "npc/combine_soldier/vo/closing.wav" },
		{ "close on suspect", "npc/metropolice/vo/allunitscloseonsuspect.wav" },
		{ "clear code 100", "npc/metropolice/vo/clearandcode100.wav" },
		{ "classify db", "npc/metropolice/vo/classifyasdbthisblockready.wav" },
		{ "citizen summoned", "npc/metropolice/vo/citizensummoned.wav" },
		{ "citizen", "npc/metropolice/vo/citizen.wav" },
		{ "proceed to checkpoints", "npc/metropolice/vo/proceedtocheckpoints.wav" },
		{ "check miscount", "npc/metropolice/vo/checkformiscount.wav" },
		{ "cauterize", "npc/metropolice/vo/cauterize.wav" },
		{ "canal block", "npc/metropolice/vo/canalblock.wav" },
		{ "canalblock", "npc/metropolice/vo/canalblock.wav" },
		{ "canal", "npc/metropolice/vo/canal.wav" },
		{ "can1", "npc/metropolice/vo/pickupthecan1.wav" },
		{ "can2", "npc/metropolice/vo/pickupthecan2.wav" },
		{ "can3", "npc/metropolice/vo/pickupthecan3.wav" },
		{ "can4", "npc/metropolice/vo/putitinthetrash1.wav" },
		{ "can5", "npc/metropolice/vo/putitinthetrash2.wav" },
		{ "can6", "npc/metropolice/vo/youknockeditover.wav" },
		{ "break cover", "npc/metropolice/vo/breakhiscover.wav" },
		{ "boomer", "npc/combine_soldier/vo/boomer.wav" },
		{ "bol 243", "npc/metropolice/vo/cpbolforthat243.wav" },
		{ "block holding", "npc/metropolice/vo/blockisholdingcohesive.wav" },
		{ "blip", "npc/metropolice/vo/catchthatbliponstabilization.wav" },
		{ "suspect is bleeding", "npc/metropolice/vo/suspectisbleeding.wav" },
		{ "backup", "npc/metropolice/vo/backup.wav" },
		{ "back me up", "npc/metropolice/vo/backmeupImout.wavv" },
		{ "at location report", "npc/metropolice/vo/ptatlocationreport.wav" },
		{ "at checkpoint", "npc/metropolice/vo/atcheckpoint.wav" },
		{ "arrest positions", "npc/metropolice/vo/movetoarrestpositions.wav" },
		{ "apply", "npc/metropolice/vo/apply.wav" },
		{ "anticitzen", "npc/metropolice/vo/anticitizen.wav" },
		{ "all units move", "npc/metropolice/vo/allunitsmovein.wav" },
		{ "affirmative", "npc/metropolice/vo/affirmative.wav" },
		{ "confirmed adw", "npc/metropolice/vo/confirmadw.wav" },
		{ "administer", "npc/metropolice/vo/administer.wav" },
		{ "acquiring", "npc/metropolice/vo/acquiringonvisual.wav" },
		{ "thats a grenade", "npc/metropolice/vo/thatsagrenade.wav" },
		{ "90", "npc/metropolice/vo/ninety.wav" },
		{ "ninety", "npc/metropolice/vo/ninety.wav" },
		{ "80", "npc/metropolice/vo/eighty.wav" },
		{ "eighty", "npc/metropolice/vo/eighty.wav" },
		{ "70", "npc/metropolice/vo/seventy.wav" },
		{ "seventy", "npc/metropolice/vo/seventy.wav" },
		{ "60", "npc/metropolice/vo/sixty.wav" },
		{ "sixty", "npc/metropolice/vo/sixty.wav" },
		{ "63", "npc/metropolice/vo/criminaltrespass63.wav" },
		{ "603", "npc/metropolice/vo/unlawfulentry603.wav" },
		{ "505", "npc/metropolice/vo/airwatchsubjectis505.wav" },
		{ "50", "npc/metropolice/vo/fifty.wav" },
		{ "fivety", "npc/metropolice/vo/fifty.wav" },
		{ "fivety", "npc/metropolice/vo/fifty.wav" },
		{ "415b", "npc/metropolice/vo/is415b.wav" },
		{ "408", "npc/metropolice/vo/Ivegot408hereatlocation.wav" },
		{ "404", "npc/metropolice/vo/404zone.wav" },
		{ "40", "npc/metropolice/vo/fourty.wav" },
		{ "fourty", "npc/metropolice/vo/fourty.wav" },
		{ "34s at", "npc/metropolice/vo/allunitsbol34sat.wav" },
		{ "300", "npc/metropolice/vo/threehundred.wav" },
		{ "three-hundred", "npc/metropolice/vo/threehundred.wav" },
		{ "30", "npc/metropolice/vo/thirty.wav" },
		{ "thirty", "npc/metropolice/vo/thirty.wav" },
		{ "200", "npc/metropolice/vo/twohundred.wav" },
		{ "two-hundred", "npc/metropolice/vo/twohundred.wav" },
		{ "20", "npc/metropolice/vo/twenty.wav" },
		{ "twenty", "npc/metropolice/vo/twenty.wav" },
		{ "10 6", "npc/metropolice/vo/suspect11-6my1020is.wav" },
		{ "11 44", "npc/metropolice/vo/get11-44inboundcleaningup.wav" },
		{ "10 99", "npc/metropolice/vo/officerdownIam10-99.wav" },
		{ "10 6", "npc/metropolice/vo/suspect11-6my1020is.wav" },
		{ "11 44", "npc/metropolice/vo/get11-44inboundcleaningup.wav" },
		{ "10 97 goa", "npc/metropolice/vo/ten97suspectisgoa.wav" },
		{ "10 97", "npc/metropolice/vo/ten97.wav" },
		{ "10 91d", "npc/metropolice/vo/ten91dcountis.wav" },
		{ "10 8 standing by", "npc/metropolice/vo/ten8standingby.wav" },
		{ "10 8", "npc/metropolice/vo/unitisonduty10-8.wav" },
		{ "10 78", "npc/metropolice/vo/dispatchIneed10-78.wav" },
		{ "10 65", "npc/metropolice/vo/unitis10-65.wav" },
		{ "10 4", "npc/metropolice/vo/ten4.wav" },
		{ "10 30", "npc/metropolice/vo/Ihave10-30my10-20responding.wav" },
		{ "10 25", "npc/metropolice/vo/unitreportinwith10-25suspect.wav" },
		{ "10 2", "npc/metropolice/vo/ten2.wav" },
		{ "10 15", "npc/metropolice/vo/preparefor1015.wav" },
		{ "10 14", "npc/metropolice/vo/holdingon10-14duty.wav" },
		{ "10 108", "npc/metropolice/vo/wehavea10-108.wav" },
		{ "10 107", "npc/metropolice/vo/gota10-107sendairwatch.wav" },
		{ "10 103 tag", "npc/metropolice/vo/possible10-103alerttagunits.wav" },
		{ "100", "npc/metropolice/vo/onehundred.wav" },
		{ "one-hundred", "npc/metropolice/vo/onehundred.wav" },
		{ "10 0 hunting", "npc/metropolice/vo/tenzerovisceratorishunting.wav" },
		{ "block", "npc/metropolice/vo/block.wav" },
		{ "location", "npc/metropolice/vo/location.wav" },
		{ "move", "npc/metropolice/vo/move.wav" },
		{ "zone", "npc/metropolice/vo/zone.wav" },
		{ "juridstiction", "npc/metropolice/vo/stabilizationjurisdiction.wav" },
		{ "necrotics", "npc/metropolice/vo/necrotics.wav" },
		{ "cover", "npc/combine_soldier/vo/coverhurt.wav" },
		{ "zero", "npc/metropolice/vo/zero.wav" },
		{ "0", "npc/metropolice/vo/zero.wav" },
		{ "one", "npc/metropolice/vo/one.wav" },
		{ "1", "npc/metropolice/vo/one.wav" },
		{ "two", "npc/metropolice/vo/two.wav" },
		{ "2", "npc/metropolice/vo/two.wav" },
		{ "three", "npc/metropolice/vo/three.wav" },
		{ "3", "npc/metropolice/vo/three.wav" },
		{ "four", "npc/metropolice/vo/four.wav" },
		{ "4", "npc/metropolice/vo/four.wav" },
		{ "five", "npc/metropolice/vo/five.wav" },
		{ "5", "npc/metropolice/vo/five.wav" },
		{ "six", "npc/metropolice/vo/six.wav" },
		{ "6", "npc/metropolice/vo/six.wav" },
		{ "seven", "npc/metropolice/vo/seven.wav" },
		{ "7", "npc/metropolice/vo/seven.wav" },
		{ "eight", "npc/metropolice/vo/eight.wav" },
		{ "8", "npc/metropolice/vo/eight.wav" },
		{ "nine", "npc/metropolice/vo/nine.wav" },
		{ "9", "npc/metropolice/vo/nine.wav" },
		{ "ten", "npc/metropolice/vo/ten.wav" },
		{ "10", "npc/metropolice/vo/ten.wav" }
	}

	local combinechat = {
		{ "administer", "npc/metropolice/vo/administer.wav" },
		{ "affirmative", "npc/metropolice/vo/affirmative.wav" },
		{ "anticitzen", "npc/metropolice/vo/anticitizen.wav" },
		{ "antiseptic", "npc/combine_soldier/vo/antiseptic.wav" },
		{ "apex", "npc/combine_soldier/vo/apex.wav" },
		{ "apply", "npc/metropolice/vo/apply.wav" },
		{ "blade", "npc/combine_soldier/vo/blade.wav" },
		{ "boomer", "npc/combine_soldier/vo/boomer.wav" },
		{ "break cover", "npc/metropolice/vo/breakhiscover.wav" },
		{ "cauterize", "npc/metropolice/vo/cauterize.wav" },
		{ "cleaned", "npc/combine_soldier/vo/cleaned.wav" },
		{ "closing", "npc/combine_soldier/vo/closing.wav" },
		{ "condemned", "npc/metropolice/vo/condemnedzone.wav" },
		{ "contact", "npc/combine_soldier/vo/contact.wav" },
		{ "contained", "npc/combine_soldier/vo/contained.wav" },
		{ "controlsection", "npc/metropolice/vo/controlsection.wav" },
		{ "control section", "npc/metropolice/vo/controlsection.wav" },
		{ "converging", "npc/metropolice/vo/converging.wav" },
		{ "copy that", "npc/combine_soldier/vo/copythat.wav" },
		{ "copy", "npc/metropolice/vo/copy.wav" },
		{ "cover", "npc/combine_soldier/vo/coverhurt.wav" },
		{ "dash", "npc/combine_soldier/vo/dash.wav" },
		{ "dagger", "npc/combine_soldier/vo/dagger.wav" },
		{ "defender", "npc/metropolice/vo/defender.wav" },
		{ "deserviced area", "npc/metropolice/vo/deservicedarea.wav" },
		{ "destroy cover", "npc/metropolice/vo/destroythatcover.wav" },
		{ "dismounting hardpoint", "npc/metropolice/vo/dismountinghardpoint.wav" },
		{ "distribution block", "npc/metropolice/vo/distributionblock.wav" },
		{ "echo", "npc/combine_soldier/vo/echo.wav" },
		{ "engaging", "npc/combine_soldier/vo/engaging.wav" },
		{ "first warning", "npc/metropolice/vo/firstwarningmove.wav" },
		{ "fist", "npc/combine_soldier/vo/fist.wav" },
		{ "flash", "npc/combine_soldier/vo/flash.wav" },
		{ "flatline", "npc/combine_soldier/vo/flatline.wav" },
		{ "flush", "npc/combine_soldier/vo/flush.wav" },
		{ "free necrotics", "npc/metropolice/vo/freenecrotics.wav" },
		{ "get out", "npc/metropolice/vo/getoutofhere.wav" },
		{ "ghost", "npc/combine_soldier/vo/ghost.wav" },
		{ "go sharp", "npc/combine_soldier/vo/gosharp.wav" },
		{ "grenade", "npc/metropolice/vo/grenade.wav" },
		{ "grid", "npc/combine_soldier/vo/grid.wav" },
		{ "hammer", "npc/combine_soldier/vo/hammer.wav" },
		{ "hardpoint scanning", "npc/metropolice/vo/hardpointscanning.wav" },
		{ "helix", "npc/combine_soldier/vo/helix.wav" },
		{ "hero", "npc/metropolice/vo/hero.wav" },
		{ "hold", "npc/metropolice/vo/holdit.wav" },
		{ "high priority region", "npc/metropolice/vo/highpriorityregion.wav" },
		{ "hpr", "npc/metropolice/vo/highpriorityregion.wav" },
		{ "hunter", "npc/combine_soldier/vo/hunter.wav" },
		{ "hurricane", "npc/combine_soldier/vo/hurricane.wav" },
		{ "i said move", "npc/metropolice/vo/Isaidmovealong.wav" },
		{ "in position", "npc/metropolice/vo/inposition.wav" },
		{ "ice", "npc/combine_soldier/vo/ice.wav" },
		{ "inbound", "npc/combine_soldier/vo/inbound.wav" },
		{ "infected", "npc/combine_soldier/vo/infected.wav" },
		{ "infection", "npc/metropolice/vo/infection.wav" },
		{ "infested zone", "npc/metropolice/vo/infestedzone.wav" },
		{ "inoculate", "npc/metropolice/vo/innoculate.wav" },
		{ "interlock", "npc/metropolice/vo/interlock.wav" },
		{ "intercede", "npc/metropolice/vo/intercede.wav" },
		{ "investigate", "npc/metropolice/vo/investigate.wav" },
		{ "ion", "npc/combine_soldier/vo/ion.wav" },
		{ "isolate", "npc/metropolice/vo/isolate.wav" },
		{ "is inbound", "npc/combine_soldier/vo/unitisinbound.wav" },
		{ "unit inbound", "npc/combine_soldier/vo/unitisinbound.wav" },
		{ "ion", "npc/metropolice/vo/ispassive.wav" },
		{ "is passive", "npc/metropolice/vo/ispassive.wav" },
		{ "is ready to go", "npc/metropolice/vo/isreadytogo.wav" },
		{ "jet", "npc/combine_soldier/vo/jet.wav" },
		{ "judge", "npc/combine_soldier/vo/judge.wav" },
		{ "jury", "npc/metropolice/vo/jury.wav" },
		{ "keep moving", "npc/metropolice/vo/keepmoving.wav" },
		{ "king", "npc/metropolice/vo/king.wav" },
		{ "kilo", "npc/combine_soldier/vo/kilo.wav" },
		{ "leader", "npc/combine_soldier/vo/leader.wav" },
		{ "line", "npc/metropolice/vo/line.wav" },
		{ "lock position", "npc/metropolice/vo/lockyourposition.wav" },
		{ "lock", "npc/metropolice/vo/lock.wav" },
		{ "loose parasitics", "npc/metropolice/vo/looseparasitics.wav" },
		{ "lost contact", "npc/combine_soldier/vo/lostcontact.wav" },
		{ "mace", "npc/combine_soldier/vo/mace.wav" },
		{ "malignant", "npc/metropolice/vo/malignant.wav" },
		{ "move along", "npc/metropolice/vo/movealong.wav" },
		{ "move back", "npc/metropolice/vo/movebackrightnow.wav" },
		{ "move it", "npc/metropolice/vo/moveit.wav" },
		{ "moving to cover", "npc/metropolice/vo/movingtocover.wav" },
		{ "moving to hardpoint", "npc/metropolice/vo/movingtohardpoint.wav" },
		{ "no contact", "npc/metropolice/vo/nocontact.wav" },
		{ "nomad", "npc/combine_soldier/vo/nomad.wav" },
		{ "noncitizen", "npc/metropolice/vo/noncitizen.wav" },
		{ "nova", "npc/combine_soldier/vo/nova.wav" },
		{ "overwatch", "npc/combine_soldier/vo/overwatch.wav" },
		{ "outbreak", "npc/combine_soldier/vo/outbreak.wav" },
		{ "pacifying", "npc/metropolice/vo/pacifying.wav" },
		{ "phantom", "npc/combine_soldier/vo/phantom.wa" },
		{ "payback", "npc/combine_soldier/vo/payback.wav" },
		{ "patrol", "npc/metropolice/vo/patrol.wav" },
		{ "position at hardpoint", "npc/metropolice/vo/inpositionathardpoint.wav" },
		{ "preserve", "npc/metropolice/vo/preserve.wav" },
		{ "pressure", "npc/metropolice/vo/pressure.wav" },
		{ "production block", "npc/metropolice/vo/productionblock.wav" },
		{ "final warning issued", "npc/metropolice/vo/readytoprosecutefinalwarning.wav" },
		{ "prosecute malcompliant", "npc/metropolice/vo/readytoprosecutefinalwarning.wav" },
		{ "final warning given", "npc/metropolice/vo/readytoprosecutefinalwarning.wav" },
		{ "final warning", "npc/metropolice/vo/finalwarning.wav" },
		{ "third warning", "npc/metropolice/vo/finalwarning.wav" },
		{ "last warning", "npc/metropolice/vo/finalwarning.wav" },
		{ "prosecute", "npc/metropolice/vo/prosecute.wav" },
		{ "prosecuting", "npc/combine_soldier/vo/prosecuting.wav" },
		{ "quicksand", "npc/combine_soldier/vo/quicksand.wav" },
		{ "quick", "npc/metropolice/vo/quick.wav" },
		{ "razor", "npc/combine_soldier/vo/razor.wav" },
		{ "ranger", "npc/combine_soldier/vo/ranger.wav" },
		{ "range", "npc/combine_soldier/vo/range.wav" },
		{ "ready amputate", "npc/metropolice/vo/readytoamputate.wav" },
		{ "ready to amputate", "npc/metropolice/vo/readytoamputate.wav" },
		{ "ready charges", "npc/combine_soldier/vo/readycharges.wav" },
		{ "ready judge", "npc/metropolice/vo/readytojudge.wav" },
		{ "ready to judge", "npc/metropolice/vo/readytojudge.wav" },
		{ "ready prosecute", "npc/metropolice/vo/readytoprosecute.wav" },
		{ "ready to prosecute", "npc/metropolice/vo/readytoprosecute.wav" },
		{ "ready weapons", "npc/combine_soldier/vo/readyweapons.wav" },
		{ "reaper", "npc/combine_soldier/vo/reaper.wav" },
		{ "reporting clear", "npc/combine_soldier/vo/reportingclear.wav" },
		{ "repurposed area", "npc/metropolice/vo/repurposedarea.wav" },
		{ "residential block", "npc/metropolice/vo/residentialblock.wav" },
		{ "responding", "npc/metropolice/vo/responding2.wav" },
		{ "restrict", "npc/metropolice/vo/restrict.wav" },
		{ "restricted block", "npc/metropolice/vo/restrictedblock.wav" },
		{ "restriction zone", "npc/metropolice/vo/terminalrestrictionzone.wav" },
		{ "ripcord", "npc/combine_soldier/vo/ripcord.wav" },
		{ "roller", "npc/metropolice/vo/roller.wav" },
		{ "hes running", "npc/metropolice/vo/hesrunning.wav" },
		{ "sacrifice code", "npc/metropolice/vo/sacrificecode1maintaincp.wav" },
		{ "savage", "npc/combine_soldier/vo/savage.wav" },
		{ "scar", "npc/combine_soldier/vo/scar.wav" },
		{ "search", "npc/metropolice/vo/search.wav" },
		{ "searching for suspect", "npc/metropolice/vo/searchingforsuspect.wav" },
		{ "second warning", "npc/metropolice/vo/thisisyoursecondwarning.wav" },
		{ "sector not sterile", "npc/combine_soldier/vo/confirmsectornotsterile.wav" },
		{ "sector not secure", "npc/combine_soldier/vo/sectorisnotsecure.wav" },
		{ "secure", "npc/combine_soldier/vo/secure.wav" },
		{ "serve", "npc/metropolice/vo/serve.wav" },
		{ "sharpzone", "npc/combine_soldier/vo/sharpzone.wav" },
		{ "shadow", "npc/combine_soldier/vo/shadow.wav" },
		{ "sociostable", "npc/metropolice/vo/wearesociostablethislocation.wav" },
		{ "slash", "npc/combine_soldier/vo/slash.wav" },
		{ "slam", "npc/combine_soldier/vo/slam.wav" },
		{ "stab", "npc/combine_soldier/vo/stab.wav" },
		{ "spear", "npc/combine_soldier/vo/spear.wav" },
		{ "standing by", "npc/combine_soldier/vo/standingby].wav" },
		{ "star", "npc/combine_soldier/vo/star.wav" },
		{ "stationblock", "npc/metropolice/vo/stationblock.wav" },
		{ "stay alert", "npc/combine_soldier/vo/stayalert.wav" },
		{ "stinger", "npc/combine_soldier/vo/stinger.wav" },
		{ "storm", "npc/combine_soldier/vo/storm.wav" },
		{ "striker", "npc/combine_soldier/vo/striker.wav" },
		{ "sundown", "npc/combine_soldier/vo/sundown.wav" },
		{ "suspend", "npc/metropolice/vo/suspend.wav" },
		{ "sweeper", "npc/combine_soldier/vo/sweeper.wav" },
		{ "sword", "npc/combine_soldier/vo/sword.wav" },
		{ "tag one necrotic", "npc/metropolice/vo/tagonenecrotic.wav" },
		{ "tag one parasitic", "npc/metropolice/vo/tagoneparasitic.wav" },
		{ "tap", "npc/metropolice/vo/tap.wav" },
		{ "target", "npc/combine_soldier/vo/target.wav" },
		{ "team holding", "npc/combine_soldier/vo/stabilizationteamholding.wav" },
		{ "administer", "npc/metropolice/vo/administer.wav" },
		{ "affirmative", "npc/metropolice/vo/affirmative2.wav" },
		{ "affirm", "npc/metropolice/vo/affirmative.wav" },
		{ "you can go", "npc/metropolice/vo/allrightyoucango.wav" },
		{ "move in", "npc/combine_soldier/vo/movein.wav" },
		{ "amputate", "npc/metropolice/vo/amputate.wav" },
		{ "anticitizen", "npc/metropolice/vo/anticitizen.wav" },
		{ "apply", "npc/metropolice/vo/apply.wav" },
		{ "backup", "npc/metropolice/vo/backup.wav" },
		{ "bugs", "npc/metropolice/vo/bugsontheloose.wav" },
		{ "cauterize", "npc/metropolice/vo/cauterize.wav" },
		{ "haha", "npc/metropolice/vo/chuckle.wav" },
		{ "citizen", "npc/metropolice/vo/citizen.wav" },
		{ "code 100", "npc/metropolice/vo/clearandcode100.wav" },
		{ "cover me", "npc/metropolice/vo/covermegoingin.wav" },
		{ "defender", "npc/metropolice/vo/defender.wav" },
		{ "document", "npc/metropolice/vo/document.wav" },
		{ "stop", "npc/metropolice/vo/dontmove.wav" },
		{ "dont move", "npc/metropolice/vo/dontmove.wav" },
		{ "don't move", "npc/metropolice/vo/dontmove.wav" },
		{ "examine", "npc/metropolice/vo/examine.wav" },
		{ "get down", "npc/metropolice/vo/getdown.wav" },
		{ "hold it right there", "npc/metropolice/vo/holditrightthere.wav" },
		{ "infection", "npc/metropolice/vo/infection.wav" },
		{ "inject", "npc/metropolice/vo/inject.wav" },
		{ "rodger", "npc/metropolice/vo/rodgerthat.wav" },
		{ "responding", "npc/metropolice/vo/responding.wav" },
		{ "sterilize", "npc/metropolice/vo/sterilize.wav" },
		{ "zero", "npc/metropolice/vo/zero.wav" },
		{ "0", "npc/metropolice/vo/zero.wav" },
		{ "xray", "npc/metropolice/vo/xray.wav" },
		{ "yellow", "npc/metropolice/vo/yellow.wav" },
		{ "zone", "npc/metropolice/vo/zone.wav" },
		{ "wrap it up", "npc/combine_soldier/vo/thatsitwrapitup.wav" },
		{ "workforce", "npc/metropolice/vo/workforceintake.wav" },
		{ "winder", "npc/combine_soldier/vo/winder.wav" },
		{ "watch it", "npc/metropolice/vo/watchit.wav" },
		{ "wasteriver", "npc/metropolice/vo/wasteriver.wav" },
		{ "second warning given", "npc/metropolice/vo/secondwarning.wav" },
		{ "visual exogen", "npc/combine_soldier/vo/visualonexogens.wav" },
		{ "viscon", "npc/combine_soldier/vo/viscon.wav" },
		{ "victor", "npc/metropolice/vo/victor.wav" },
		{ "vice", "npc/metropolice/vo/vice.wav" },
		{ "vamp", "npc/combine_soldier/vo/vamp.wav"},
		{ "vacate", "npc/metropolice/vo/vacatecitizen.wav" },
		{ "up there", "npc/metropolice/vo/hesupthere.wav" },
		{ "suspect location unknown", "npc/metropolice/vo/suspectlocationunknown.wav" },
		{ "location", "npc/metropolice/vo/location.wav" },
		{ "union", "npc/metropolice/vo/union.wav" },
		{ "uniform", "npc/combine_soldier/vo/uniform.wav" },
		{ "under fire", "npc/metropolice/vo/officerunderfiretakingcover.wav" },
		{ "trouble", "npc/metropolice/vo/lookingfortrouble.wav" },
		{ "transitblock", "npc/metropolice/vo/transitblock.wav" },
		{ "tracker", "npc/combine_soldier/vo/tracker.wav" },
		{ "there he is", "npc/metropolice/vo/thereheis.wav" },
		{ "team advance", "npc/metropolice/vo/teaminpositionadvance.wav" },
		{ "90", "npc/metropolice/vo/ninety.wav" },
		{ "ninety", "npc/metropolice/vo/ninety.wav" },
		{ "80", "npc/metropolice/vo/eighty.wav" },
		{ "eighty", "npc/metropolice/vo/eighty.wav" },
		{ "70", "npc/metropolice/vo/seventy.wav" },
		{ "seventy", "npc/metropolice/vo/seventy.wav" },
		{ "60", "npc/metropolice/vo/sixty.wav" },
		{ "sixty", "npc/metropolice/vo/sixty.wav" },
		{ "50", "npc/metropolice/vo/fifty.wav" },
		{ "fivety", "npc/metropolice/vo/fifty.wav" },
		{ "fivety", "npc/metropolice/vo/fifty.wav" },
		{ "404", "npc/metropolice/vo/404zone.wav" },
		{ "40", "npc/metropolice/vo/fourty.wav" },
		{ "fourty", "npc/metropolice/vo/fourty.wav" },
		{ "300", "npc/metropolice/vo/threehundred.wav" },
		{ "three-hundred", "npc/metropolice/vo/threehundred.wav" },
		{ "30", "npc/metropolice/vo/thirty.wav" },
		{ "thirty", "npc/metropolice/vo/thirty.wav" },
		{ "200", "npc/metropolice/vo/twohundred.wav" },
		{ "two-hundred", "npc/metropolice/vo/twohundred.wav" },
		{ "20", "npc/metropolice/vo/twenty.wav" },
		{ "twenty", "npc/metropolice/vo/twenty.wav" },
		{ "100", "npc/metropolice/vo/onehundred.wav" },
		{ "one-hundred", "npc/metropolice/vo/onehundred.wav" },
		{ "block", "npc/metropolice/vo/block.wav" },
		{ "location", "npc/metropolice/vo/location.wav" },
		{ "move", "npc/metropolice/vo/move.wav" },
		{ "zone", "npc/metropolice/vo/zone.wav" },
		{ "juridstiction", "npc/metropolice/vo/stabilizationjurisdiction.wav" },
		{ "necrotics", "npc/metropolice/vo/necrotics.wav" },
		{ "cover", "npc/combine_soldier/vo/coverhurt.wav" },
		{ "zero", "npc/metropolice/vo/zero.wav" },
		{ "0", "npc/metropolice/vo/zero.wav" },
		{ "one", "npc/metropolice/vo/one.wav" },
		{ "1", "npc/metropolice/vo/one.wav" },
		{ "two", "npc/metropolice/vo/two.wav" },
		{ "2", "npc/metropolice/vo/two.wav" },
		{ "three", "npc/metropolice/vo/three.wav" },
		{ "3", "npc/metropolice/vo/three.wav" },
		{ "four", "npc/metropolice/vo/four.wav" },
		{ "4", "npc/metropolice/vo/four.wav" },
		{ "five", "npc/metropolice/vo/five.wav" },
		{ "5", "npc/metropolice/vo/five.wav" },
		{ "six", "npc/metropolice/vo/six.wav" },
		{ "6", "npc/metropolice/vo/six.wav" },
		{ "seven", "npc/metropolice/vo/seven.wav" },
		{ "7", "npc/metropolice/vo/seven.wav" },
		{ "eight", "npc/metropolice/vo/eight.wav" },
		{ "8", "npc/metropolice/vo/eight.wav" },
		{ "nine", "npc/metropolice/vo/nine.wav" },
		{ "9", "npc/metropolice/vo/nine.wav" },
		{ "ten", "npc/metropolice/vo/ten.wav" },
		{ "10", "npc/metropolice/vo/ten.wav" }
	}

	local femalechat = {
		{ "ammo", "vo/npc/female01/ammo03.wav" },
		{ "behind you", "vo/npc/female01/behindyou01.wav" },
		{ "better reload", "vo/npc/female01/youdbetterreload01.wav" },
		{ "bullshit", "vo/npc/female01/question26.wav" },
		{ "cheese", "vo/npc/female01/question06.wav" },
		{ "combine", "vo/npc/female01/combine01.wav" },
		{ "coming", "vo/npc/female01/squad_approach04.wav" },
		{ "cops", "vo/npc/female01/civilprotection01.wav" },
		{ "cp", "vo/npc/female01/civilprotection01.wav" },
		{ "civil protection", "vo/npc/female01/civilprotection01.wav" },
		{ "cut it", "vo/trainyard/female01/cit_hit01.wav" },
		{ "dont tell me", "vo/npc/female01/gordead_ans03.wav" },
		{ "excuse me", "vo/npc/female01/excuseme01.wav" },
		{ "fantastic", "vo/npc/female01/fantastic01.wav" },
		{ "figures", "vo/npc/female01/answer03.wav" },
		{ "finally", "vo/npc/female01/finally.wav" },
		{ "follow", "vo/coast/odessa/female01/stairman_follow01.wav" },
		{ "freeman", "vo/npc/female01/freeman.wav" },
		{ "get down", "vo/npc/female01/getdown02.wav" },
		{ "get in", "vo/canals/gunboat_getin.wav" },
		{ "get out", "vo/npc/female01/gethellout.wav" },
		{ "good god", "vo/npc/female01/goodgod.wav" },
		{ "got one", "vo/npc/female01/gotone01.wav" },
		{ "gotta reload", "vo/npc/female01/gottareload01.wav" },
		{ "hacks", "vo/npc/female01/hacks02.wav" },
		{ "hax", "vo/npc/female01/hacks02.wav" },
		{ "help", "vo/npc/female01/help01.wav" },
		{ "hello", "vo/npc/female01/hi02.wav" },
		{ "hi", "vo/npc/female01/hi01.wav" },
		{ "heads up", "vo/npc/female01/headsup01.wav" },
		{ "i know", "vo/npc/female01/answer08.wav" },
		{ "isnt good", "vo/trainyard/female01/cit_window_use01.wav" },
		{ "ok", "vo/npc/female01/answer02.wav" },
		{ "okay", "vo/npc/female01/answer02.wav" },
		{ "lets go", "vo/npc/female01/letsgo01.wav" },
		{ "let's go", "vo/npc/female01/letsgo01.wav" },
		{ "never", "vo/Citadel/eli_nonever.wav" },
		{ "nice", "vo/npc/female01/nice.wav" },
		{ "no", "vo/npc/female01/no01.wav" },
		{ "not sure", "vo/npc/female01/answer21.wav" },
		{ "now what", "vo/npc/female01/gordead_ans01.wav" },
		{ "oops", "vo/npc/female01/whoops01.wav" },
		{ "over here", "vo/npc/female01/overhere01.wav" },
		{ "over there", "vo/npc/female01/overthere01.wav" },
		{ "run", "vo/npc/female01/strider_run.wav" },
		{ "shut up", "vo/npc/female01/answer17.wav" },
		{ "sorry", "vo/npc/female01/sorry01.wav" },
		{ "take cover", "vo/npc/female01/takecover02.wav" },
		{ "uh oh", "vo/npc/female01/uhoh.wav" },
		{ "wait", "vo/trainyard/man_waitaminute.wav" },
		{ "watch out", "vo/npc/female01/watchout.wav" },
		{ "what now", "vo/npc/female01/gordead_ques16.wav" },
		{ "yea", "vo/npc/female01/yeah02.wav" },
		{ "yes", "vo/npc/female01/yeah02.wav" }
	}

	local malechat = {
		{ "ammo", "vo/npc/male01/ammo03.wav" },
		{ "behind you", "vo/npc/male01/behindyou01.wav" },
		{ "better reload", "vo/npc/male01/youdbetterreload01.wav" },
		{ "bullshit", "vo/npc/male01/question26.wav" },
		{ "cheese", "vo/npc/male01/question06.wav" },
		{ "combine", "vo/npc/male01/combine01.wav" },
		{ "coming", "vo/npc/male01/squad_approach04.wav" },
		{ "cops", "vo/npc/male01/civilprotection01.wav" },
		{ "cp", "vo/npc/male01/civilprotection01.wav" },
		{ "cut it", "vo/trainyard/male01/cit_hit01.wav" },
		{ "dont tell me", "vo/npc/male01/gordead_ans03.wav" },
		{ "excuse me", "vo/npc/male01/excuseme01.wav" },
		{ "fantastic", "vo/npc/male01/fantastic01.wav" },
		{ "figures", "vo/npc/male01/answer03.wav" },
		{ "finally", "vo/npc/male01/finally.wav" },
		{ "follow", "vo/coast/odessa/male01/stairman_follow01.wav" },
		{ "freeman", "vo/npc/male01/freeman.wav" },
		{ "get down", "vo/npc/male01/getdown02.wav" },
		{ "get in", "vo/canals/gunboat_getin.wav" },
		{ "get out", "vo/npc/male01/gethellout.wav" },
		{ "good god", "vo/npc/male01/goodgod.wav" },
		{ "got one", "vo/npc/male01/gotone01.wav" },
		{ "gotta reload", "vo/npc/male01/gottareload01.wav" },
		{ "hacks", "vo/npc/male01/hacks02.wav" },
		{ "hax", "vo/npc/male01/hacks02.wav" },
		{ "help", "vo/npc/male01/help01.wav" },
		{ "hello", "vo/npc/male01/hi02.wav" },
		{ "hi", "vo/npc/male01/hi01.wav" },
		{ "heads up", "vo/npc/male01/headsup01.wav" },
		{ "i know", "vo/npc/male01/answer08.wav" },
		{ "isnt good", "vo/trainyard/male01/cit_window_use01.wav" },
		{ "ok", "vo/npc/male01/answer02.wav" },
		{ "okay", "vo/npc/male01/answer02.wav" },
		{ "lets go", "vo/npc/male01/letsgo01.wav" },
		{ "let's go", "vo/npc/male01/letsgo01.wav" },
		{ "never", "vo/Citadel/eli_nonever.wav" },
		{ "nice", "vo/npc/male01/nice.wav" },
		{ "no", "vo/Citadel/br_no.wav" },
		{ "not sure", "vo/npc/male01/answer21.wav" },
		{ "now what", "vo/npc/male01/gordead_ans01.wav" },
		{ "oops", "vo/npc/male01/whoops01.wav" },
		{ "over here", "vo/npc/male01/overhere01.wav" },
		{ "over there", "vo/npc/male01/overthere01.wav" },
		{ "run", "vo/npc/male01/strider_run.wav" },
		{ "shut up", "vo/npc/male01/answer17.wav" },
		{ "sorry", "vo/npc/male01/sorry01.wav" },
		{ "take cover", "vo/npc/male01/takecover02.wav" },
		{ "uh oh", "vo/npc/male01/uhoh.wav" },
		{ "wait", "vo/trainyard/man_waitaminute.wav" },
		{ "watch out", "vo/npc/male01/watchout.wav" },
		{ "what now", "vo/npc/male01/gordead_ques16.wav" },
		{ "yea", "vo/npc/male01/yeah02.wav" },
		{ "yes", "vo/npc/male01/yeah02.wav" }
	}

	--Credit to DarkRP devs for parts of this function that correctly verify text
	local function CheckText( tbl, text, ply )
		for _,v in pairs( tbl ) do
			local res1, res2 = string.find( string.lower( text ), v[1] )
			if res1 and ( !text[res1 - 1] or text[res1 - 1] == "" or text[res1 - 1] == " " ) and ( !text[res2 + 1] or text[res2 + 1] == "" or text[res2 + 1] == " " ) then
				ply:EmitSound( v[2], 80, 100 )
				break
			end
		end
	end

	--Plays sounds based on what players send in chat, similar to what DarkRP does but with support for specific sounds for specific playermodels
	hook.Add( "PlayerSay", "SoundChat", function( ply, text, team )
		--if team then return end -- this line disables the voicelines in team chat(u)
		local prefixlist = { "!", "@" } -- "/"
		local model = ply:GetModel()
		if table.HasValue( prefixlist, string.sub( text, 0, 1 ) ) then return end
		if ply.chatcooldown and ply.chatcooldown > CurTime() then return end
		if scimodels[model] then
			CheckText( scichats, text, ply )
		elseif secmodels[model] then
			CheckText( secchats, text, ply )
		elseif marinemodels[model] then
			CheckText( marinechats, text, ply )
		elseif cpmodels[model] then
			CheckText( cpchat, text, ply )
		elseif combinemodels[model] then
			CheckText( combinechat, text, ply )
		elseif femalemodels[model] then
			CheckText( femalechat, text, ply )
		elseif malemodels[model] then
			CheckText( malechat, text, ply )
		end
		return text
	end )
end

hook.Add("InitPostEntity", "InitializeSoundChatAfterJobs", InitializeSoundChat)